### ISSUE TITLE
Please set your email address in Git config

### ISSUE THREAD

**Issue by tedokon** [miri4ech/php_kadais#2]
@miri4ech 

## Document

- [Setting your email in Git - User Documentation](https://help.github.com/articles/setting-your-email-in-git/)
- [Setting your username in Git - User Documentation](https://help.github.com/articles/setting-your-username-in-git/)

## Example

```
$ git config --global user.email "john@apple.com"
$ git config --global user.name "John Appleseed"
```

**Comment by miri4ech** [comment]
@tedokon set done !

**Comment by tedokon** [comment]
@miri4ech 
good! 👍
