### ISSUE TITLE
Cannot reproduce: todo-mysql2.php

### ISSUE THREAD

**Issue by tedokon** [miri4ech/php_kadais#7]
@miri4ech 

## Problems

- `items2` テーブルは `CREATE TABLE` ステートメントを使って、新規で作成するように実装してください。
- また、スクリプトが複数回実行された場合のことを考慮し、`CREATE TABLE` が最初の1回だけ実行されるようにしてください。
  - ヒント: [MySQL :: MySQL 5.5 Reference Manual :: 13.1.10 CREATE DATABASE Syntax](https://dev.mysql.com/doc/refman/5.5/en/create-database.html)

:
:

Please fix it!

**Comment by miri4ech** [comment]
@tedokon 
直接mysqlに入れてました！
php fileに追加しましたので、ご確認お願いします！
[変更commit](https://github.com/miri4ech/php_kadais/commit/fd0c3ddf52ea4f427ccaa9ac2e35519e8ffa76d8)

**Comment by tedokon** [comment]
@miri4ech 
👍
