### ISSUE TITLE
Cannot reproduce: todo_mysql2.php

### ISSUE THREAD

**Issue by tedokon** [miri4ech/php_kadais#8]
@miri4ech 

## Problems

- [todo_mysql2.php](https://github.com/miri4ech/php_kadais/blob/fd0c3ddf52ea4f427ccaa9ac2e35519e8ffa76d8/kadai_vol4/todo_mysql2.php)

```
//二重投稿防止
if($_SERVER['REQUEST_METHOD']==='POST'){
	//kunisadaのlocalhostの設定
	header('Location:http://local-tasks.com/kadai_vol4/todo_mysql2.php');	
}
```

この記述ですと、他の環境で動作しませんので、他の方法を検討してください！

### ヒント

- http://php.net/manual/en/function.header.php#refsect1-function.header-notes

**Comment by miri4ech** [comment]
@tedokon 
対応しました！気をつけますね^^
vol5の方も同じことしてたので、同じく修正していますー！

**Comment by tedokon** [comment]
@miri4ech 
なおってました！ 👍
